name: Test-Action

on:
  push:
    branches: [video]

jobs:
  testing:
    runs-on: ubuntu-latest
    env: 
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_DB: ${{ env.PG_NAME }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready 
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Проверка изменений
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
                  
      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Линтер
        run: flake8 webpython --exclude migrations --ignore E902,E501,F401,E302,W293,W391,W292

      - name: tests
        run: python 3.2-crud/stocks_products/manage.py test logistic
        env:
          PG_NAME: ${{ env.PG_NAME }}
          PG_USER: ${{ env.PG_USER }}
          PG_PASSWORD: ${{ env.PG_PASSWORD }}
          PG_HOST: ${{ env.PG_HOST }}
          PG_PORT: ${{ env.PG_PORT }}
    deploy:
        runs-on: ubuntu-latest
        needs: testing
        steps:
          - name: deploy
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              script:
                cd /root/dj-homeworks/3.2-crud/stocks_products
                git pull
                sudo systemctl restart gunicorn 
