name: Test-Action

on:
        push:
                branches: [main]

jobs:
        testing:
                runs-on: ubuntu-latest
                env:
                        PG_NAME: ${{ secrets.PG_NAME }}
                        PG_USER: ${{ secrets.PG_USER }}
                        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
                        PG_HOST: ${{ secrets.PG_HOST }}
                        PG_PORT: ${{ secrets.PG_PORT }}
                steps:
                       -name: Проверка изменений
                        uses: actions/checkout@v2

                       -name: Установка Python
                        uses: actions/setup-python@v5
                        with:
                                python-version: 3.12
                       -name: Установка зависимостей
                        run: pip install -r requirements.txt

                       -name: Линтер
                        run: flake8 webpython --exclude migrations --ignore E501,F401,E302,W293,W391,W292
